kind: pipeline
name: default

workspace:
  base: /app
  path: src/github.com/omropfryslan/docker-atlassian-jira

steps:
  - name: build-and-update
    image: circleci/ruby
    commands:
      - bin/prepare
      - docker build .
