kind: pipeline
name: default

steps:
- name: build-and-update
  image: docker
  privileged: true
  commands:
    - apk add --no-cache --update curl git
    - bin/prepare
    - docker build .
    - bin/deploy
  volumes:
    - name: docker
      path: /var/run/docker.sock

- name: docker
  image: plugins/docker
  settings:
    repo: omropfryslan/docker-atlassian-jira
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
